#include <stdio.h>
#include <stdlib.h>

int main(int argc, char **argv)
{
    FILE *in, *out;
    int c;
    unsigned long n = 0;
    const char *name = "exelink_template_exe";
    if (argc < 3 || argc > 4)
    {
        fprintf(stderr, "usage: bin2c input output [symbol]\n");
        return 2;
    }
    if (argc == 4)
        name = argv[3];
    in = fopen(argv[1], "rb");
    if (!in)
    {
        perror(argv[1]);
        return 1;
    }
    out = fopen(argv[2], "w");
    if (!out)
    {
        perror(argv[2]);
        fclose(in);
        return 1;
    }
    fprintf(out, "/* Generated by bin2c. */\n#include <stddef.h>\nconst unsigned char %s[] = {", name);
    while ((c = fgetc(in)) != EOF)
    {
        if ((n % 12) == 0)
            fputs("\n    ", out);
        fprintf(out, "0x%02x,", (unsigned char)c);
        ++n;
    }
    fprintf(out, "\n};\nconst size_t %s_size = %luu;\n", name, n);
    if (ferror(in) || ferror(out))
    {
        fclose(out);
        fclose(in);
        return 1;
    }
    fclose(out);
    fclose(in);
    return 0;
}
